version: '3.3'

services:
  webapi:
    build:
      context: ./SampleProject
      dockerfile: Dockerfile
    user: "1000:1000"   # <-- Run as non-root appuser
    depends_on:
      - mysql
      - redis
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=/run/secrets/mysql_database;user=/run/secrets/mysql_user;password=/run/secrets/mysql_root_password
      - Redis__Host=redis
      - Redis__Port=6379
      - ASPNETCORE_ENVIRONMENT=Development
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_database
    volumes:
      - webapi_logs:/app/logs
    networks:
      - sample_network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_database
    networks:
      - sample_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sample_network

volumes:
  mysql_data:
  redis_data:
  webapi_logs:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_database:
    file: ./secrets/mysql_database.txt

networks:
  sample_network:
    driver: bridge