version: '3.3'

services:
  webapi:
    build:
      context: ./SampleProject
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=paymentdb;user=root;password=secret
      - Redis__Host=redis 
      - Redis__Port=6379 
      - ASPNETCORE_ENVIRONMENT=Development

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: paymentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:

